import React, { useState, useEffect } from "react";
import Modal from "../../ui/Modal";
import {
  getClientInvoiceByCompanyApi,
  type CompanyClientInvoiceData,
} from "../../../api/financeApi/clientInvoiceApi";
import { toast } from "react-toastify";
import Select from "../../ui/Select";
import { StatusBadge } from "../../ui/StatusBadge";
import { ChevronLeft, ChevronRight } from "lucide-react";

// FIXED: Import the timezone formatter so Created At renders consistently
import { formatDateTime } from "../../../helper/dateFormatter";

interface ClientInvoiceViewClientModalProps {
  isOpen: boolean;
  onClose: () => void;
  companyName: string | null;
  companyInvoiceId: number | null;
}

const rowsOptions = [
  { value: "10", label: "10" },
  { value: "25", label: "25" },
  { value: "50", label: "50" },
  { value: "100", label: "100" },
];

// const formatDateToday = () => {
//   const date = new Date();
//   const year = date.getFullYear();
//   const month = String(date.getMonth() + 1).padStart(2, "0");
//   const day = String(date.getDate()).padStart(2, "0");
//   return `${year}-${month}-${day}`;
// };

export const ClientInvoiceViewClientModal: React.FC<ClientInvoiceViewClientModalProps> = ({
  isOpen,
  onClose,
  companyName,
  companyInvoiceId,
}) => {
  const [allInvoices, setAllInvoices] = useState<CompanyClientInvoiceData[]>(
    [],
  );
  const [isLoading, setIsLoading] = useState(false);

  const [currentPage, setCurrentPage] = useState(1);
  const [rowsPerPage, setRowsPerPage] = useState(50);

  useEffect(() => {
    if (isOpen && companyInvoiceId) {
      fetchInvoices();
    } else {
      setAllInvoices([]);
    }
    setCurrentPage(1);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, companyInvoiceId]);

  const fetchInvoices = async () => {
    if (!companyInvoiceId) return;
    setIsLoading(true);
    try {
      const res = await getClientInvoiceByCompanyApi(companyInvoiceId);
      const list = res.results || (Array.isArray(res) ? res : []);
      setAllInvoices(list);
    } catch (err) {
      console.error(err);
      toast.error("Failed to load client invoices.");
    } finally {
      setIsLoading(false);
    }
  };

  const totalItems = allInvoices.length;
  const totalPages = Math.ceil(totalItems / rowsPerPage) || 1;
  const startIndex = (currentPage - 1) * rowsPerPage;
  const pagedInvoices = allInvoices.slice(startIndex, startIndex + rowsPerPage);
  const paginationLabel = `${totalItems === 0 ? 0 : startIndex + 1}-${Math.min(
    startIndex + pagedInvoices.length,
    totalItems,
  )} of ${totalItems}`;

  const currencyCode =
    allInvoices.length > 0 ? allInvoices[0].currencyCode : "";

  // NOTE: these 5 columns are fixed ("locked") — always shown, not part of
  // any column-visibility toggle, matching the main table's editable columns.
  const headers = [
    "Invoice No.",
    "Client Name",
    "Period Start",
    "Period End",
    "Invoice Date",
    "Total Segments",
    `Total Amount ${currencyCode ? `(${currencyCode})` : ""}`,
    "Tax %",
    `Tax Amount ${currencyCode ? `(${currencyCode})` : ""}`,
    "Currency",
    "Created At",
    "Status",
    "Generated By",
  ];

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={`Client Invoices: ${companyName || ""}`}
      className="max-w-full w-full"
    >
      <div className="p-4 w-full min-w-0 flex flex-col">
        <div className="flex items-center mb-4 gap-3 bg-gray-50 dark:bg-gray-800/50 p-2.5 rounded-lg border border-gray-200 dark:border-gray-700 w-full shrink-0">
          <p className="text-[13px] text-gray-600 dark:text-gray-300 leading-tight">
            <span className="font-medium text-gray-900 dark:text-gray-100">
              Displaying Invoices:
            </span>{" "}
            Shows invoices for this company as of today.
          </p>
        </div>

        {/* Pagination bar */}
        <div className="flex items-center mb-3 gap-4 flex-wrap">
          <div className="flex items-center space-x-2">
            <span className="text-sm text-text-secondary dark:text-gray-400 whitespace-nowrap">
              Rows per page:
            </span>
            <div className="w-24 shrink-0">
              <Select
                value={String(rowsPerPage)}
                onChange={(val: string) => {
                  setRowsPerPage(Number(val));
                  setCurrentPage(1);
                }}
                options={rowsOptions}
                clearable={false}
                placement="bottom"
              />
            </div>
          </div>
          <span className="text-sm text-text-secondary dark:text-gray-400 whitespace-nowrap">
            {paginationLabel}
          </span>
          <div className="flex items-center space-x-2 shrink-0">
            <button
              className="rounded border border-transparent p-1 text-gray-400 hover:text-primary hover:bg-gray-100 dark:hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              onClick={() => setCurrentPage((p) => Math.max(p - 1, 1))}
              disabled={currentPage === 1 || isLoading}
            >
              <ChevronLeft size={20} />
            </button>
            <button
              className="rounded border border-transparent p-1 text-gray-400 hover:text-primary hover:bg-gray-100 dark:hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              onClick={() =>
                setCurrentPage((p) => Math.min(p + 1, totalPages))
              }
              disabled={currentPage >= totalPages || totalItems === 0 || isLoading}
            >
              <ChevronRight size={20} />
            </button>
          </div>
        </div>

        <div className="overflow-x-auto border border-gray-200 dark:border-gray-700 rounded-lg custom-scrollbar w-full min-w-0">
          <table className="w-full text-left border-collapse text-sm">
            <thead>
              <tr className="bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 border-b border-gray-200 dark:border-gray-600">
                {headers.map((h, i) => (
                  <th key={i} className="py-3 px-4 font-medium whitespace-nowrap">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {isLoading ? (
                <tr>
                  <td colSpan={headers.length} className="text-center py-8 text-gray-500">
                    Loading invoices...
                  </td>
                </tr>
              ) : pagedInvoices.length === 0 ? (
                <tr>
                  <td colSpan={headers.length} className="text-center py-8 text-gray-500">
                    No invoices found.
                  </td>
                </tr>
              ) : (
                pagedInvoices.map((inv) => (
                  <tr
                    key={inv.id}
                    className="border-b border-gray-100 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors"
                  >
                    <td className="py-3 px-4 font-medium text-primary whitespace-nowrap">
                      {inv.invoiceNumber || "-"}
                    </td>
                    <td className="py-3 px-4 text-text-secondary dark:text-gray-300 whitespace-nowrap">
                      {inv.clientName || inv.companyName || "-"}
                    </td>
                    <td className="py-3 px-4 text-text-secondary dark:text-gray-300 whitespace-nowrap">
                      {inv.billingPeriodStart || "-"}
                    </td>
                    <td className="py-3 px-4 text-text-secondary dark:text-gray-300 whitespace-nowrap">
                      {inv.billingPeriodEnd || "-"}
                    </td>
                    <td className="py-3 px-4 text-text-secondary dark:text-gray-300 whitespace-nowrap">
                      {inv.invoiceDate || "-"}
                    </td>
                    <td className="py-3 px-4 text-text-secondary dark:text-gray-300 whitespace-nowrap">
                      {inv.totalSegments ?? "-"}
                    </td>
                    <td className="py-3 px-4 text-text-secondary dark:text-gray-300 font-medium whitespace-nowrap">
                      {inv.totalAmount != null && !isNaN(Number(inv.totalAmount))
                        ? Number(inv.totalAmount).toFixed(4)
                        : "-"}
                    </td>
                    <td className="py-3 px-4 text-text-secondary dark:text-gray-300 whitespace-nowrap">
                      {inv.taxPercentage != null && !isNaN(Number(inv.taxPercentage))
                        ? `${Number(inv.taxPercentage).toFixed(2)}%`
                        : "-"}
                    </td>
                    <td className="py-3 px-4 text-text-secondary dark:text-gray-300 whitespace-nowrap">
                      {inv.taxAmount != null && !isNaN(Number(inv.taxAmount))
                        ? Number(inv.taxAmount).toFixed(4)
                        : "-"}
                    </td>
                    <td className="py-3 px-4 text-text-secondary dark:text-gray-300 whitespace-nowrap">
                      {inv.currencyCode || "-"}
                    </td>
                    <td className="py-3 px-4 text-text-secondary dark:text-gray-300 whitespace-nowrap">
                      {inv.createdAt ? formatDateTime(inv.createdAt) : "-"}
                    </td>
                    <td className="py-3 px-4">
                      <StatusBadge status={inv.status} />
                    </td>
                    <td className="py-3 px-4 text-text-secondary dark:text-gray-300 whitespace-nowrap">
                      {inv.accountManagerName || "-"}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </Modal>
  );
};