import React, { useState, useEffect, useMemo } from "react";
import Modal from "../../ui/Modal";
import ModalDataTable from "../../ui/ModalDataTable";
import {
  getVendorInvoiceByCompanyApi,
  type CompanyVendorInvoiceData,
} from "../../../api/financeApi/vendorInvoiceApi";
import { toast } from "react-toastify";
import { StatusBadge } from "../../ui/StatusBadge";
import { formatDateTime } from "../../../helper/dateFormatter";

interface VendorInvoiceViewVendorModalProps {
  isOpen: boolean;
  onClose: () => void;
  companyName: string | null;
  companyInvoiceId: number | null;
}

const DEFAULT_COLUMNS = [
  "invoiceNumber",
  "vendorName",
  "billingPeriodStart",
  "billingPeriodEnd",
  "invoiceDate",
  "totalSegments",
  "totalAmount",
  "taxPercentage",
  "taxAmount",
  "currencyCode",
  "createdAt",
  "status",
  "accountManagerName",
];

export const VendorInvoiceViewVendorModal: React.FC<VendorInvoiceViewVendorModalProps> = ({
  isOpen,
  onClose,
  companyName,
  companyInvoiceId,
}) => {
  const [allInvoices, setAllInvoices] = useState<CompanyVendorInvoiceData[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const [columns, setColumns] = useState<string[]>(DEFAULT_COLUMNS);
  const [sortConfig, setSortConfig] = useState<{ key: string; direction: "asc" | "desc" } | null>(null);

  const [currentPage, setCurrentPage] = useState(1);
  const [rowsPerPage, setRowsPerPage] = useState(50);

  useEffect(() => {
    if (!isOpen) {
      setAllInvoices([]);
      setSortConfig(null);
      setCurrentPage(1);
    }
  }, [isOpen]);

  useEffect(() => {
    if (isOpen && companyInvoiceId) {
      fetchInvoices();
    } else {
      setAllInvoices([]);
    }
    setCurrentPage(1);
  }, [isOpen, companyInvoiceId]);

  const fetchInvoices = async () => {
    if (!companyInvoiceId) return;
    setIsLoading(true);
    try {
      const res = await getVendorInvoiceByCompanyApi(companyInvoiceId);
      const list = res.results || (Array.isArray(res) ? res : []);
      setAllInvoices(list);
    } catch (err) {
      console.error(err);
      toast.error("Failed to load vendor invoices.");
    } finally {
      setIsLoading(false);
    }
  };

  const currencyCode = allInvoices.length > 0 ? allInvoices[0].currencyCode : "";

  const COLUMN_LABELS: Record<string, string> = {
    invoiceNumber: "Invoice No.",
    vendorName: "Vendor Name",
    billingPeriodStart: "Period Start",
    billingPeriodEnd: "Period End",
    invoiceDate: "Invoice Date",
    totalSegments: "Total Segments",
    totalAmount: `Total Amount ${currencyCode ? `(${currencyCode})` : ""}`,
    taxPercentage: "Tax %",
    taxAmount: `Tax Amount ${currencyCode ? `(${currencyCode})` : ""}`,
    currencyCode: "Currency",
    createdAt: "Created At",
    status: "Status",
    accountManagerName: "Generated By",
  };

  const handleSort = (idx: number) => {
    const colKey = columns[idx];
    if (!colKey) return;
    setSortConfig((prev) => {
      if (prev?.key === colKey) {
        if (prev.direction === "asc") return { key: colKey, direction: "desc" };
        return null;
      }
      return { key: colKey, direction: "asc" };
    });
  };

  const handleReorderColumns = (fromIdx: number, toIdx: number) => {
    setColumns((prev) => {
      const next = [...prev];
      const [moved] = next.splice(fromIdx, 1);
      next.splice(toIdx, 0, moved);
      return next;
    });
  };

  const sortedInvoices = useMemo(() => {
    if (!sortConfig) return allInvoices;
    return [...allInvoices].sort((a: any, b: any) => {
      let aVal = a[sortConfig.key];
      let bVal = b[sortConfig.key];
      if (sortConfig.key === "totalAmount" || sortConfig.key === "taxAmount" || sortConfig.key === "totalSegments") {
        aVal = Number(aVal) || 0;
        bVal = Number(bVal) || 0;
      }
      if (aVal === bVal) return 0;
      if (aVal == null) return 1;
      if (bVal == null) return -1;
      const res = aVal > bVal ? 1 : -1;
      return sortConfig.direction === "asc" ? res : -res;
    });
  }, [allInvoices, sortConfig]);

  const renderCell = (colKey: string, inv: any) => {
    switch (colKey) {
      case "invoiceNumber":
        return <td key={colKey} className="py-2.5 px-3 font-medium text-primary whitespace-nowrap">{inv.invoiceNumber || "-"}</td>;
      case "vendorName":
        return <td key={colKey} className="py-2.5 px-3 text-text-secondary dark:text-gray-300 whitespace-nowrap">{inv.vendorName || inv.companyName || "-"}</td>;
      case "billingPeriodStart":
        return <td key={colKey} className="py-2.5 px-3 text-text-secondary dark:text-gray-300 whitespace-nowrap">{inv.billingPeriodStart || "-"}</td>;
      case "billingPeriodEnd":
        return <td key={colKey} className="py-2.5 px-3 text-text-secondary dark:text-gray-300 whitespace-nowrap">{inv.billingPeriodEnd || "-"}</td>;
      case "invoiceDate":
        return <td key={colKey} className="py-2.5 px-3 text-text-secondary dark:text-gray-300 whitespace-nowrap">{inv.invoiceDate || "-"}</td>;
      case "totalSegments":
        return <td key={colKey} className="py-2.5 px-3 text-text-secondary dark:text-gray-300 whitespace-nowrap">{inv.totalSegments ?? "-"}</td>;
      case "totalAmount":
        return (
          <td key={colKey} className="py-2.5 px-3 text-text-secondary dark:text-gray-300 font-medium whitespace-nowrap">
            {inv.totalAmount != null && !isNaN(Number(inv.totalAmount)) ? Number(inv.totalAmount).toFixed(4) : "-"}
          </td>
        );
      case "taxPercentage":
        return (
          <td key={colKey} className="py-2.5 px-3 text-text-secondary dark:text-gray-300 whitespace-nowrap">
            {inv.taxPercentage != null && !isNaN(Number(inv.taxPercentage)) ? `${Number(inv.taxPercentage).toFixed(2)}%` : "-"}
          </td>
        );
      case "taxAmount":
        return (
          <td key={colKey} className="py-2.5 px-3 text-text-secondary dark:text-gray-300 whitespace-nowrap">
            {inv.taxAmount != null && !isNaN(Number(inv.taxAmount)) ? Number(inv.taxAmount).toFixed(4) : "-"}
          </td>
        );
      case "currencyCode":
        return <td key={colKey} className="py-2.5 px-3 text-text-secondary dark:text-gray-300 whitespace-nowrap">{inv.currencyCode || "-"}</td>;
      case "createdAt":
        return <td key={colKey} className="py-2.5 px-3 text-text-secondary dark:text-gray-300 whitespace-nowrap">{inv.createdAt ? formatDateTime(inv.createdAt) : "-"}</td>;
      case "status":
        return <td key={colKey} className="py-2.5 px-3"><StatusBadge status={inv.status} /></td>;
      case "accountManagerName":
        return <td key={colKey} className="py-2.5 px-3 text-text-secondary dark:text-gray-300 whitespace-nowrap">{inv.accountManagerName || "-"}</td>;
      default:
        return <td key={colKey} className="py-2.5 px-3 text-text-secondary dark:text-gray-300 whitespace-nowrap">{inv[colKey] || "-"}</td>;
    }
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={`Vendor Invoices: ${companyName || ""}`}
      className="max-w-full w-full"
    >
      <div className="p-4 w-full min-w-0 flex flex-col">
        <div className="flex items-center mb-4 gap-3 bg-gray-50 dark:bg-gray-800/50 p-2.5 rounded-lg border border-gray-200 dark:border-gray-700 w-full shrink-0">
          <p className="text-[13px] text-gray-600 dark:text-gray-300 leading-tight">
            <span className="font-medium text-gray-900 dark:text-gray-100">
              Displaying Invoices:
            </span>{" "}
            Shows invoices for this company as of today.
          </p>
        </div>

        <ModalDataTable
          data={sortedInvoices}
          headers={columns.map((c) => COLUMN_LABELS[c] || c)}
          renderRow={(inv) => (
            <tr
              key={inv.id}
              className="border-b border-gray-100 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors"
            >
              {columns.map((colKey) => renderCell(colKey, inv))}
            </tr>
          )}
          isLoading={isLoading}
          serverSide={false}
          currentPage={currentPage}
          rowsPerPage={rowsPerPage}
          onPageChange={setCurrentPage}
          onRowsPerPageChange={(rows) => { setRowsPerPage(rows); setCurrentPage(1); }}
          onReorderColumns={handleReorderColumns}
          onSort={handleSort}
          sortColumnIndex={sortConfig ? columns.findIndex((c) => c === sortConfig.key) : null}
          sortDirection={sortConfig?.direction || null}
          columnKeys={columns}
          storageKey="vendor_invoice_modal_table"
          emptyMessage="No invoices found."
        />
      </div>
    </Modal>
  );
};

export default VendorInvoiceViewVendorModal;